### PR TITLE
Implement support for RAK2287

### PR DESCRIPTION
**Pull request by papadkostas**

### CODE REVIEW

**Comment by brocaar** [comment]
Thanks @papadkostas  :+1:

**Comment by papadkostas** [comment]
I've made a mistake and build failed.
Needs the following.
`diff --git a/chirpstack-concentratord-sx1302/src/config/vendor/rak/mod.rs b/chirpstack-concentratord-sx1302/src/config/vendor/rak/mod.rs
index 178de9f..594d057 100644
--- a/chirpstack-concentratord-sx1302/src/config/vendor/rak/mod.rs
+++ b/chirpstack-concentratord-sx1302/src/config/vendor/rak/mod.rs
@@ -1,7 +1,7 @@
-pub mod rak2287_as923.rs;
-pub mod rak2287_au915.rs;
-pub mod rak2287_eu868.rs;
-pub mod rak2287_in865.rs;
-pub mod rak2287_kr920.rs;
-pub mod rak2287_ru864.rs;
-pub mod rak2287_us915.rs;
+pub mod rak2287_as923;
+pub mod rak2287_au915;
+pub mod rak2287_eu868;
+pub mod rak2287_in865;
+pub mod rak2287_kr920;
+pub mod rak2287_ru864;
+pub mod rak2287_us915;`

**Comment by brocaar** [comment]
I just noticed :) I forgot to enable pull-request builds for this repo, so the tests did not run. I'll fix this.

**Comment by brocaar** [comment]
@papadkostas must the power_en_pin be set? See the original sx1302 reset script:

https://github.com/Lora-net/sx1302_hal/blob/master/tools/reset_lgw.sh#L16

**Comment by brocaar** [comment]
@papadkostas could you please test the above changes on your Raspberry Pi to confirm if all is working?

**Comment by papadkostas** [comment]
@brocaar I'm trying to but docker-compose gives me an error for some packages.
E: Package 'gcc-arm-linux-gnueabi' has no installation candidate
E: Package 'g++-arm-linux-gnueabi' has no installation candidate
E: Package 'gcc-arm-linux-gnueabihf' has no installation candidate
E: Package 'g++-arm-linux-gnueabihf' has no installation candidate

I'm building it directly on my Pi. I haven't modified the docker file.

**Comment by brocaar** [comment]
I would recommend that you build on an AMD64 machine and run `make build-armv7hf-release`, that will cross-compile a binary that you can use on a Pi :)

**Comment by papadkostas** [comment]
Ok, so I've managed to compile it, run the binary and got into an error.

**Comment by papadkostas** [comment]
Ok, so I've managed to compile it, run the binary and got into an error.

**Comment by papadkostas** [comment]
Ok, so I've managed to compile it, run the binary on my Pi and got into an error.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "lgw_txgain_setconf failed"', src/libcore/result.rs:1165:5

> @papadkostas must the power_en_pin be set? See the original sx1302 reset script:
> 
> https://github.com/Lora-net/sx1302_hal/blob/master/tools/reset_lgw.sh#L16

The RAK2287 got no SX1302_POWER_EN_PIN, SX1261_RESET_PIN, AD5338R_RESET_PIN.
I've opened the shield and found out only the 2 sx1251 and the sx1302.

**Comment by brocaar** [comment]
> Ok, so I've managed to compile it, run the binary on my Pi and got into an error.
thread 'main' panicked at 'called Result::unwrap() on an Err value: "lgw_txgain_setconf failed"', src/libcore/result.rs:1165:5
SPI is enabled on my Pi

At this point it is really hard for me to tell what is going wrong. I hope to receive one of these shields soon so that I can do further testing.

**Comment by papadkostas** [comment]
Ok, I'll try to figure it out in the meantime.
Just found this.
https://www.github.com/brocaar/chirpstack-concentratord/tree/master/Dockerfile-devel#L57

**Comment by papadkostas** [comment]
@brocaar this module needs a modified sx1302_hal because it doesn't have few components on it. I confirmed that with rak release of pkt_fwd. How can I make it build the binary with my modified repository of sx1302_hal? Just edit the Dockerfile-devel?

**Comment by brocaar** [comment]
Do you know what modifications were made to the sx1302 hal / where we can
find the codebase for this? See the Dockerfile-devel (
https://github.com/brocaar/chirpstack-concentratord/blob/master/Dockerfile-devel)
where the HAL libraries are cloned and (cross)compile.

**Comment by papadkostas** [comment]
@brocaar these are the only required changes for sx1302_hal, commenting out errors 😁 
[sx1302_hal-1.0.5_rak2287.patch.txt](https://github.com/brocaar/chirpstack-concentratord/files/6111656/sx1302_hal-1.0.5_rak2287.patch.txt)
Is that critical to apply rssi compensation for received packets to crash the whole concentrator if a sensor stops working or somehow reading is impossible? Wondering why semtech haven't integrated a temperature sensor on chip.

**Comment by dougreese** [comment]
Although this PR was merged, I am having some problems getting the RAK2287 support working with a US915 configuration.  I started a [thread on the forum](https://forum.chirpstack.io/t/err-lgw-txgain-setconf-failed/10912).  Maybe a new issue would be better? Which is preferred for this type of discussion, where support for a new concentrator is being added?

**Comment by brocaar** [comment]
I finally have received all parts so that I can test this myself (the RAK2287 Pi converter shield came in yesterday). I'm planning to test this in the next few days - week.

@papadkostas thanks for sharing the diff!

> Wondering why semtech haven't integrated a temperature sensor on chip.

I have a SX1302 CoreCell from Semtech and it does have the sensor I believe :)

Anyway, will test soon! I have a bunch of devices on my desk which I'm currently testing and this mode is one of these :)

**Comment by papadkostas** [comment]
@brocaar the temperature comes from a separate IC, not the concentrator IC. If you'll need anything let us know :)

**Comment by brocaar** [comment]
@dougreese @papadkostas thanks for the input! Please re-test with the latest master version. Don't forget to run `docker-compose build`, you also might want to remove the `target` folder to make sure you are compiling against the latest HAL.

**Comment by dougreese** [comment]
@brocaar I have it built and running on RPi.  If I run into any problems I will open a new issue or PR.

**Pull request merged**
